from pybricks.parameters import Port

LEFT_MOTOR_PORT = Port.A
RIGHT_MOTOR_PORT = Port.C

WHEEL_DIAMETER = 52.5
AXLE_TRACK = 153

TURNING_P = 1.5
TURNING_I = 0.000005
TURNING_D = 0.0001

STRAIGHT_P = 2
STRAIGHT_I = 0.00001
STRAIGHT_D = 0

CLAW_MOTOR_PORT = Port.B

SENSOR_1_PORT = Port.S1
BOTTOM_OBJECT_SENSOR_PORT = Port.S2
SENSOR_3_PORT = Port.S3
GYRO_PORT = Port.S4

CLAW_COLOR_SENSOR_PORT = Port.S1
OBSTACLE_SENSOR_PORT = Port.S2
TOP_OBJECT_SENSOR_PORT = Port.S3

CLAW_COLOR_SENSOR_MAILBOX = 'mb1'
OBSTACLE_SENSOR_MAILBOX = 'm2'
TOP_OBJECT_SENSOR_MAILBOX = 'mb3'

SERVER_NAME = 'CV-EV3-1'
CLIENT_NAME = 'CV-EV3-2'

POSSIBLE_OBSTACLE_SQUARES = [(0, 2), (0, 4), (1, 1), (1, 3), (2, 2), (2, 4), (3, 1), (3, 3), (4, 2), (4, 4)]
